"""
Tests for analyzers.video_analyzer.VideoAnalyzer.

Phase 24 — video container decomposition. The analyzer walks the ISO
BMFF (MP4 / MOV) box stream and the EBML (WEBM / MKV) head, then
routes each extracted stem to the analyzer that already knows how to
read that material:

  * Subtitle text → ``ZahirTextAnalyzer._check_unicode`` + regex-based
    HTML-injection shape detectors.
  * Cover-art / thumbnail image bytes → ``ImageAnalyzer().scan``.

These tests pin:

  * The BaseAnalyzer contract (inheritance, class attributes,
    supported_kinds, instantiability, return shape).
  * Each video mechanism fires on its dedicated fixture and only that
    mechanism (plus the always-on ``video_stream_inventory``).
  * The composition path actually reaches the delegated analyzer —
    ``subtitle_invisible_chars`` uses the exact codepoint set
    ZahirTextAnalyzer operates on, and ``video_frame_stego_candidate``
    fires when the cover-art image itself would fire an ImageAnalyzer
    finding.
  * Negative / edge cases (missing file, zero-byte input, extension-
    only fallback, mis-magic) return well-formed reports without
    propagating exceptions.

Fixture walker at ``tests/test_video_fixtures.py`` exercises the full
``ScanService`` dispatch path. The guardrails here stay at the
analyzer level.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from analyzers import VideoAnalyzer
from analyzers.base import BaseAnalyzer
from domain import IntegrityReport
from domain.config import (
    BIDI_CONTROL_CHARS,
    SEVERITY,
    TIER,
    ZAHIR_MECHANISMS,
    BATIN_MECHANISMS,
    ZERO_WIDTH_CHARS,
)
from infrastructure.file_router import FileKind


# ---------------------------------------------------------------------------
# Fixture paths — generated by tests/make_video_fixtures.py
# ---------------------------------------------------------------------------

FIXTURES_DIR: Path = (
    Path(__file__).resolve().parent.parent / "fixtures" / "video"
)


@pytest.fixture(scope="module", autouse=True)
def _ensure_video_fixtures_built() -> None:
    """Regenerate video fixtures if any are missing.

    The fixtures are deterministic (no timestamps, no randomness) so
    regeneration is byte-identical when everything already exists.
    """
    from tests.make_video_fixtures import (
        VIDEO_FIXTURE_EXPECTATIONS,
        generate_all,
    )
    missing = [
        FIXTURES_DIR / rel
        for rel in VIDEO_FIXTURE_EXPECTATIONS
        if not (FIXTURES_DIR / rel).exists()
    ]
    if missing:
        generate_all(FIXTURES_DIR)


# ---------------------------------------------------------------------------
# Contract
# ---------------------------------------------------------------------------


def test_is_base_analyzer_subclass() -> None:
    assert issubclass(VideoAnalyzer, BaseAnalyzer)


def test_class_attributes() -> None:
    assert VideoAnalyzer.name == "video"
    assert VideoAnalyzer.error_prefix == "Video scan error"
    assert VideoAnalyzer.source_layer == "batin"


def test_supported_kinds_covers_four_video_families() -> None:
    expected = frozenset({
        FileKind.VIDEO_MP4,
        FileKind.VIDEO_MOV,
        FileKind.VIDEO_WEBM,
        FileKind.VIDEO_MKV,
    })
    assert VideoAnalyzer.supported_kinds == expected


def test_supported_kinds_excludes_non_video_families() -> None:
    # Disjoint from every pre-Phase-24 analyzer's supported_kinds. A
    # regression here would mean VideoAnalyzer fires on a PDF / image /
    # DOCX and that would break the additive-only parity contract.
    for kind in (
        FileKind.PDF, FileKind.DOCX, FileKind.XLSX, FileKind.PPTX,
        FileKind.HTML, FileKind.EML, FileKind.CSV, FileKind.JSON,
        FileKind.IMAGE_PNG, FileKind.IMAGE_JPEG, FileKind.IMAGE_SVG,
        FileKind.MARKDOWN, FileKind.CODE, FileKind.UNKNOWN,
    ):
        assert kind not in VideoAnalyzer.supported_kinds, (
            f"VideoAnalyzer must not advertise support for {kind}"
        )


def test_instantiable() -> None:
    a = VideoAnalyzer()
    assert a.name == "video"
    assert "VideoAnalyzer" in repr(a)


# ---------------------------------------------------------------------------
# Mechanism registry coherence — every mechanism VideoAnalyzer emits
# must be registered in domain/config.py.
# ---------------------------------------------------------------------------


_VIDEO_MECHANISMS: set[str] = {
    "video_stream_inventory",
    "subtitle_injection",
    "subtitle_invisible_chars",
    "video_metadata_suspicious",
    "video_embedded_attachment",
    "video_frame_stego_candidate",
    "video_container_anomaly",
    "video_cross_stem_divergence",
}


def test_every_video_mechanism_is_registered() -> None:
    combined = ZAHIR_MECHANISMS | BATIN_MECHANISMS
    missing = _VIDEO_MECHANISMS - combined
    assert not missing, f"unregistered video mechanisms: {missing}"


def test_every_video_mechanism_has_severity_and_tier() -> None:
    for m in _VIDEO_MECHANISMS:
        assert m in SEVERITY, f"{m} missing SEVERITY"
        assert m in TIER, f"{m} missing TIER"
        assert 0.0 <= SEVERITY[m] <= 1.0
        assert TIER[m] in (1, 2, 3)


def test_subtitle_mechanisms_are_zahir() -> None:
    # Subtitle concealment is zahir — the viewer sees the rendered text;
    # the stream carries different codepoints. Mirrors the PDF text-
    # layer classification in config.py.
    assert "subtitle_injection" in ZAHIR_MECHANISMS
    assert "subtitle_invisible_chars" in ZAHIR_MECHANISMS


def test_non_subtitle_video_mechanisms_are_batin() -> None:
    for m in (
        "video_stream_inventory",
        "video_metadata_suspicious",
        "video_embedded_attachment",
        "video_frame_stego_candidate",
        "video_container_anomaly",
        "video_cross_stem_divergence",
    ):
        assert m in BATIN_MECHANISMS, f"{m} should be batin-classified"


def test_stream_inventory_is_non_deducting() -> None:
    # The inventory is informational meta-output, not a deduction. A
    # non-zero severity would penalise every video for being scanned.
    assert SEVERITY["video_stream_inventory"] == 0.0


# ---------------------------------------------------------------------------
# Negative / edge cases
# ---------------------------------------------------------------------------


def test_missing_file_returns_scan_error_and_incomplete() -> None:
    r = VideoAnalyzer().scan(Path("/definitely/does/not/exist.mp4"))
    assert isinstance(r, IntegrityReport)
    assert r.scan_incomplete is True
    assert r.integrity_score == 0.0
    mechs = [f.mechanism for f in r.findings]
    assert mechs == ["scan_error"]
    assert r.error is not None
    assert "File not found" in r.error


def test_zero_byte_file_surfaces_container_anomaly(tmp_path: Path) -> None:
    # An empty file with a video extension routes through the extension-
    # only fallback → VideoAnalyzer → video_container_anomaly.
    empty = tmp_path / "empty.mp4"
    empty.write_bytes(b"")
    r = VideoAnalyzer().scan(empty)
    mechs = [f.mechanism for f in r.findings]
    assert "video_container_anomaly" in mechs


def test_garbage_bytes_in_mp4_extension_fires_anomaly(tmp_path: Path) -> None:
    # Extension says .mp4 but bytes are clearly neither ISO BMFF nor
    # EBML. The analyzer emits a container anomaly rather than silent-
    # clean.
    junk = tmp_path / "junk.mp4"
    junk.write_bytes(b"not a video file at all, just text")
    r = VideoAnalyzer().scan(junk)
    mechs = {f.mechanism for f in r.findings}
    assert "video_container_anomaly" in mechs


def test_clean_fixture_returns_only_inventory() -> None:
    r = VideoAnalyzer().scan(FIXTURES_DIR / "clean" / "clean.mp4")
    mechs = {f.mechanism for f in r.findings}
    assert mechs == {"video_stream_inventory"}
    # Score must be 1.0 — inventory is non-deducting.
    assert r.integrity_score == 1.0
    assert r.scan_incomplete is False


# ---------------------------------------------------------------------------
# Per-mechanism adversarial fixtures
# ---------------------------------------------------------------------------


def _scan_adversarial(name: str) -> IntegrityReport:
    return VideoAnalyzer().scan(FIXTURES_DIR / "adversarial" / name)


def test_subtitle_invisible_chars_fires() -> None:
    r = _scan_adversarial("subtitle_invisible_chars.mp4")
    mechs = {f.mechanism for f in r.findings}
    assert "subtitle_invisible_chars" in mechs
    assert r.integrity_score < 1.0


def test_subtitle_injection_fires() -> None:
    r = _scan_adversarial("subtitle_injection.mp4")
    mechs = {f.mechanism for f in r.findings}
    assert "subtitle_injection" in mechs
    assert r.integrity_score < 1.0


def test_metadata_suspicious_fires() -> None:
    r = _scan_adversarial("metadata_suspicious.mp4")
    mechs = {f.mechanism for f in r.findings}
    assert "video_metadata_suspicious" in mechs
    assert r.integrity_score < 1.0


def test_embedded_attachment_fires_on_free_box_polyglot() -> None:
    r = _scan_adversarial("embedded_attachment.mp4")
    mechs = {f.mechanism for f in r.findings}
    assert "video_embedded_attachment" in mechs
    assert r.integrity_score < 1.0


def test_cover_art_stego_delegates_to_image_analyzer() -> None:
    # The composition path: cover-art PNG with trailing data → written
    # through ImageAnalyzer → re-emitted under video_frame_stego_candidate.
    r = _scan_adversarial("cover_art_stego.mp4")
    mechs = {f.mechanism for f in r.findings}
    assert "video_frame_stego_candidate" in mechs
    assert r.integrity_score < 1.0


def test_trailing_data_fires_container_anomaly() -> None:
    r = _scan_adversarial("trailing_data.mp4")
    mechs = {f.mechanism for f in r.findings}
    assert "video_container_anomaly" in mechs


def test_mdat_polyglot_fires_container_anomaly() -> None:
    r = _scan_adversarial("mdat_polyglot.mp4")
    mechs = {f.mechanism for f in r.findings}
    assert "video_container_anomaly" in mechs


def test_mkv_attachments_element_fires_embedded_attachment() -> None:
    r = _scan_adversarial("attachments.mkv")
    mechs = {f.mechanism for f in r.findings}
    assert "video_embedded_attachment" in mechs


def test_cross_stem_divergence_fixture_does_not_false_positive() -> None:
    # The cross-stem divergence detector is future work; the fixture
    # exists to prove the current analyzer does not fire spuriously on
    # a legally-multilingual file.
    r = _scan_adversarial("cross_stem_divergence.mp4")
    mechs = {f.mechanism for f in r.findings}
    assert "video_cross_stem_divergence" not in mechs
    # Score remains 1.0 — only inventory, which is non-deducting.
    assert r.integrity_score == 1.0


# ---------------------------------------------------------------------------
# Composition verification
# ---------------------------------------------------------------------------


def test_subtitle_invisible_chars_routes_through_zahir_text_analyzer() -> None:
    """Composition invariant: subtitle_invisible_chars must use the
    exact codepoint universe ZahirTextAnalyzer uses for PDF spans.

    Regression guard — if someone hardcodes a new zero-width set in
    VideoAnalyzer, the two analyzers can drift and the same byte
    sequence in a subtitle vs a PDF would classify differently. We
    assert that every codepoint the ZahirTextAnalyzer treats as
    zero-width is also what VideoAnalyzer's subtitle pipeline sees.
    """
    r = _scan_adversarial("subtitle_invisible_chars.mp4")
    finding = next(
        (f for f in r.findings if f.mechanism == "subtitle_invisible_chars"),
        None,
    )
    assert finding is not None
    # The concealed field carries the offending codepoint U+ labels
    # that ZahirTextAnalyzer's helper reported; at least one must be
    # from the shared ZERO_WIDTH_CHARS or BIDI_CONTROL_CHARS set.
    concealed = finding.concealed or ""
    zw_labels = {f"U+{ord(c):04X}" for c in ZERO_WIDTH_CHARS}
    bidi_labels = {f"U+{ord(c):04X}" for c in BIDI_CONTROL_CHARS}
    assert any(lbl in concealed for lbl in zw_labels | bidi_labels), (
        f"Expected a shared-universe codepoint label in: {concealed!r}"
    )


def test_cover_art_stego_preserves_underlying_image_evidence() -> None:
    """Composition invariant: the video_frame_stego_candidate finding
    preserves the ImageAnalyzer sub-mechanism name in its ``surface``
    so a forensics reader can trace which image-layer detector fired.
    """
    r = _scan_adversarial("cover_art_stego.mp4")
    finding = next(
        (f for f in r.findings if f.mechanism == "video_frame_stego_candidate"),
        None,
    )
    assert finding is not None
    # The surface string records the inherited mechanism name.
    assert "inherited from ImageAnalyzer" in (finding.surface or "")


# ---------------------------------------------------------------------------
# Return-shape / structural guarantees
# ---------------------------------------------------------------------------


def test_scan_always_returns_integrity_report() -> None:
    # For every fixture we emit, the return must be an IntegrityReport.
    # No analyzer may leak None, list, or dict at the contract surface.
    cases = [
        FIXTURES_DIR / "clean" / "clean.mp4",
        FIXTURES_DIR / "adversarial" / "subtitle_injection.mp4",
        FIXTURES_DIR / "adversarial" / "trailing_data.mp4",
        FIXTURES_DIR / "adversarial" / "attachments.mkv",
        Path("/definitely/does/not/exist.mp4"),
    ]
    for p in cases:
        r = VideoAnalyzer().scan(p)
        assert isinstance(r, IntegrityReport)
        assert isinstance(r.integrity_score, float)
        assert 0.0 <= r.integrity_score <= 1.0
        assert isinstance(r.findings, list)
        for f in r.findings:
            # Every finding carries a registered mechanism (including
            # scan_error which lives in the batin set).
            assert f.mechanism in (ZAHIR_MECHANISMS | BATIN_MECHANISMS), (
                f"unregistered mechanism leaked: {f.mechanism}"
            )


def test_no_exceptions_propagate_for_adversarial_fixtures() -> None:
    # The analyzer must be defensive: malformed inputs produce findings,
    # not exceptions. Regression guard against ``except OSError``-only
    # blocks that miss a ValueError inside struct.unpack, etc.
    for rel in (
        "adversarial/subtitle_invisible_chars.mp4",
        "adversarial/subtitle_injection.mp4",
        "adversarial/metadata_suspicious.mp4",
        "adversarial/embedded_attachment.mp4",
        "adversarial/cover_art_stego.mp4",
        "adversarial/trailing_data.mp4",
        "adversarial/mdat_polyglot.mp4",
        "adversarial/cross_stem_divergence.mp4",
        "adversarial/attachments.mkv",
    ):
        # This may not raise.
        VideoAnalyzer().scan(FIXTURES_DIR / rel)
